### ISSUE TITLE
Consider using preprocessor sequences

### ISSUE THREAD

**Issue by badair** [gerritdaniels/ctrl#2]
[Preprocessor sequences](http://www.boost.org/doc/libs/1_60_0/libs/preprocessor/doc/data/sequences.html) could clean up the macro interface a bit. How do you feel about a syntax like this?

```
    class SimpleClass
    {
         CTRL_MEMBERS(SimpleClass,
             ((private, int, m_count))
             ((private, std::string, m_name))
         )
    };
```

> As you can see the example for the map is a bit more involving, you need to define a typedef first. This is always the case if you want to use types that have multiple template parameters.

Prepreocessor sequences can also solve this problem.

Edit: fixed bad link
Edit: [Here](http://stackoverflow.com/questions/26475453/how-to-use-boostpreprocessor-to-unzip-a-sequence) is an example usage. Also, FWIW, [this](http://badair.github.io/callable_traits/doc/html/callable_traits_interface_example.html) is the only code I've written that uses the technique. It's not easy to follow, even for me, but there it is if you need it.

**Comment by gerritdaniels** [comment]
I implemented a [more boost compliant](https://github.com/gerritdaniels/reflection) version that uses its preprocessor meta programming library and serialization framework.

But this framework doesn't support controlling the output (eg. field as attribute instead of element) like ctrl does with its annotation like macros. And also has no json serializer backend. So I'm not integrating it in this project.
